name             'jira_war_distribution'
maintainer       'Martin Fleischer'
maintainer_email 'martin.t.fleischer@gmail.com'
license          'All rights reserved'
description      'Installs/Configures jira_war_distribution'
long_description 'Installs/Configures jira_war_distribution'
version          '0.1.0'

depends 'apt'
depends 'tomcat'
