name             'jira_war_distribution'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jira_war_distribution'
long_description 'Installs/Configures jira_war_distribution'
version          '0.1.0'

depends 'apt'
depends 'tomcat'
